
[manager]
cwd = { fg = "#1c1c1c" }
hovered = { reversed = true, bold = true }
preview_hovered = { underline = true }
find_keyword = { fg = "#ff6c6b", italic = true }
find_position = { fg = "#51afef", bg = "reset", italic = true }
marker_copied = { fg = "#98be65", bg = "#98be65" }
marker_cut = { fg = "#da8548", bg = "#da8548" }
marker_marked = { fg = "#51afef", bg = "#51afef" }
marker_selected = { fg = "#f8f8f2", bg = "#f8f8f2" }
tab_active = { fg = "#f8f8f2", bg = "#51afef" }
tab_inactive = { fg = "#1c1c1c", bg = "#d0d0d0" }
tab_width = 1
count_copied = { fg = "#f8f8f2", bg = "#98be65" }
count_cut = { fg = "#f8f8f2", bg = "#da8548" }
count_selected = { fg = "#f8f8f2", bg = "#f8f8f2" }
border_symbol = "│"
border_style = { fg = "#b0b0b0" }

[mode]
normal_main = { fg = "#f8f8f2", bg = "#51afef", bold = true }
normal_alt = { fg = "#1c1c1c", bg = "#d0d0d0" }
select_main = { fg = "#f8f8f2", bg = "#da8548", bold = true }
select_alt = { fg = "#1c1c1c", bg = "#d0d0d0" }
unset_main = { fg = "#f8f8f2", bg = "#98be65", bold = true }
unset_alt = { fg = "#1c1c1c", bg = "#d0d0d0" }

[status]
sep_left = { open = "\ue0be", close = "\ue0b8" }
sep_right = { open = "\ue0be", close = "\ue0b8" }
overall = { }
progress_label = { fg = "#f8f8f2", bold = true }
progress_normal = { fg = "#d0d0d0", bg = "#1c1c1c" }
progress_error = { fg = "#da8548", bg = "#1c1c1c" }
perm_type = { fg = "#d0d0d0" }
perm_read = { fg = "#98be65" }
perm_write = { fg = "#da8548" }
perm_exec = { fg = "#98be65" }
perm_sep = { fg = "#b0b0b0" }

[pick]
border = { fg = "#51afef" }
active = { fg = "#da8548", bold = true }
inactive = { }

[input]
border = { fg = "#f8f8f2" }
title = { }
value = { }
selected = { reversed = true }

[tasks]
border = { fg = "#51afef" }
title = { }
hovered = { underline = true }

[which]
mask = { bg = "#f8f8f2" }
cand = { fg = "#51afef" }
rest = { fg = "#b0b0b0" }
desc = { fg = "#da8548" }
separator = "  "
separator_style = { fg = "#d0d0d0" }

[help]
on = { fg = "#51afef" }
run = { fg = "#da8548" }
hovered = { reversed = true, bold = true }
footer = { fg = "#f8f8f2", bg = "#51afef" }

[notify]
title_info = { fg = "#51afef" }
title_warn = { fg = "#f8f8f2" }
title_error = { fg = "#da8548" }

[filetype]
rules = [
  { mime = "image/*", fg = "#da8548" },
  { mime = "{audio,video}/*", fg = "#51afef" },
  { mime = "application/*zip", fg = "#da8548" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#da8548" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#98be65" },
  { name = "*", fg = "#f8f8f2" },
  { name = "*/", fg = "#51afef" },
]

[confirm]
border = { fg = "#51afef" }
title = { fg = "#51afef" }
content = { fg = "#f8f8f2" }
body = { fg = "red" }
list = { fg = "#f8f8f2" }
btn_yes = { reversed = true, fg = "#f8f8f2" }
btn_no = { }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[cmp]
border = { fg = "#51afef" }
active = { reversed = true, fg = "#51afef" }
inactive = { fg = "#f8f8f2" }
