# : Manager [[[

[mgr]
cwd = { fg = "#4C4F69" }

# Tab
tab_active = { fg = "#fbf1c7", bg = "#4C4F69", bold = true }
tab_inactive = { fg = "#4C4F69", bg = "#6C6F85" }
tab_width = 1

# Find
find_keyword = { fg = "#D20F39", bold = true, italic = true, underline = true }
find_position = { fg = "#D20F39", bold = true, italic = true }

# Marker
marker_copied = { fg = "#40A02B", bg = "#40A02B" }
marker_cut = { fg = "#282828", bg = "#282828" }
marker_marked = { fg = "#4C4F69", bg = "#4C4F69" }
marker_selected = { fg = "#bcbfcb", bg = "#bcbfcb" }

# Count
count_copied = { fg = "#EFF1F5", bg = "#282828" }
count_cut = { fg = "#EFF1F5", bg = "#282828" }
count_selected = { fg = "#fbf1c7", bg = "#bcbfcb" }

# Border
border_symbol = " "
border_style  = { fg = "#4C4F69" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#6C6F85", fg = "#4C4F69" }

[mode]
# Mode
normal_main = { bg = "#4C4F69", fg = "#fbf1c7", bold = true }
normal_alt  = { bg = "#ACB0BE", fg = "#4C4F69" }

# Select mode
select_main = { bg = "#282828", fg = "#282828", bold = true }
select_alt  = { bg = "#ACB0BE", fg = "#4C4F69" }

# Unset mode
unset_main = { bg = "#bcbfcb", fg = "#282828", bold = true }
unset_alt  = { bg = "#ACB0BE", fg = "#4C4F69" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#4C4F69", bg = "#ACB0BE" }
progress_error = { fg = "#40A02B", bg = "#ACB0BE" }

# Permissions
permissions_t = { fg = "#4C4F69" }
permissions_w = { fg = "#bcbfcb" }
permissions_x = { fg = "#40A02B" }
permissions_r = { fg = "#4C4F69" }
permissions_s = { fg = "#282828" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#4C4F69" }
active = { fg = "#bcbfcb", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#4C4F69" }
value = { fg = "#4C4F69" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#4C4F69", bold = true, bg = "#EFF1F5" }
inactive = { fg = "#282828", bg = "#EFF1F5" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#4C4F69", bg = "#6C6F85" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#4C4F69" }
title = {}
hovered = { fg = "#282828", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#ACB0BE" }
cand = { fg = "#4C4F69" }
rest = { fg = "#fbf1c7" }
desc = { fg = "#4C4F69" }
separator = " ‚ñ∂ "
separator_style = { fg = "#4C4F69" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#4C4F69" }
run = { fg = "#4C4F69" }
footer = { fg = "#282828", bg = "#282828" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#bcbfcb" }
title_warn = { fg = "#4C4F69" }
title_error = { fg = "#40A02B" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#bcbfcb" },

    # Media
    { mime = "{audio,video}/*", fg = "#4C4F69" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#282828" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#4C4F69" },

    # Special files
    { name = "*", is = "orphan", bg = "#40A02B" },
    { name = "*", is = "exec", fg = "#282828" },

    # Fallback
    { name = "*", fg = "#4C4F69" },
    { name = "*/", fg = "#4C4F69" },
]

# : ]]]
