
[manager]
cwd = { fg = "#dc8a78" }
hovered = { reversed = true, bold = true }
preview_hovered = { underline = true }
find_keyword = { fg = "#dc8a78", italic = true }
find_position = { fg = "#ea76cb", bg = "reset", italic = true }
marker_copied = { fg = "#ea76cb", bg = "#ea76cb" }
marker_cut = { fg = "#ea76cb", bg = "#ea76cb" }
marker_marked = { fg = "#dc8a78", bg = "#dc8a78" }
marker_selected = { fg = "#f5e0dc", bg = "#f5e0dc" }
tab_active = { fg = "#eff1f5", bg = "#dc8a78" }
tab_inactive = { fg = "#dc8a78", bg = "#dce0e8" }
tab_width = 1
count_copied = { fg = "#eff1f5", bg = "#ea76cb" }
count_cut = { fg = "#eff1f5", bg = "#ea76cb" }
count_selected = { fg = "#eff1f5", bg = "#f5e0dc" }
border_symbol = "│"
border_style = { fg = "#b8b8b8" }

[mode]
normal_main = { fg = "#eff1f5", bg = "#dc8a78", bold = true }
normal_alt = { fg = "#dc8a78", bg = "#dce0e8" }
select_main = { fg = "#eff1f5", bg = "#ea76cb", bold = true }
select_alt = { fg = "#dc8a78", bg = "#dce0e8" }
unset_main = { fg = "#eff1f5", bg = "#ea76cb", bold = true }
unset_alt = { fg = "#dc8a78", bg = "#dce0e8" }

[status]
sep_left = { open = "\ue0be", close = "\ue0b8" }
sep_right = { open = "\ue0be", close = "\ue0b8" }
overall = { }
progress_label = { fg = "#eff1f5", bold = true }
progress_normal = { fg = "#dce0e8", bg = "#ffffff" }
progress_error = { fg = "#ea76cb", bg = "#ffffff" }
perm_type = { fg = "#dce0e8" }
perm_read = { fg = "#dc8a78" }
perm_write = { fg = "#ea76cb" }
perm_exec = { fg = "#dc8a78" }
perm_sep = { fg = "#b8b8b8" }

[pick]
border = { fg = "#dc8a78" }
active = { fg = "#ea76cb", bold = true }
inactive = { }

[input]
border = { fg = "#eff1f5" }
title = { }
value = { }
selected = { reversed = true }

[tasks]
border = { fg = "#dc8a78" }
title = { }
hovered = { underline = true }

[which]
mask = { bg = "#ffffff" }
cand = { fg = "#dc8a78" }
rest = { fg = "#b8b8b8" }
desc = { fg = "#ea76cb" }
separator = "  "
separator_style = { fg = "#dce0e8" }

[help]
on = { fg = "#dc8a78" }
run = { fg = "#ea76cb" }
hovered = { reversed = true, bold = true }
footer = { fg = "#ffffff", bg = "#dc8a78" }

[notify]
title_info = { fg = "#dc8a78" }
title_warn = { fg = "#f5e0dc" }
title_error = { fg = "#ea76cb" }

[filetype]
rules = [
  { mime = "image/*", fg = "#ea76cb" },
  { mime = "{audio,video}/*", fg = "#f5c2e7" },
  { mime = "application/*zip", fg = "#ea76cb" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ea76cb" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#dc8a78" },
  { name = "*", fg = "#eff1f5" },
  { name = "*/", fg = "#dc8a78" },
]

[confirm]
border = { fg = "#dc8a78" }
title = { fg = "#dc8a78" }
content = { fg = "#f5e0dc" }
body = { fg = "red" }
list = { fg = "#eff1f5" }
btn_yes = { reversed = true, fg = "#eff1f5" }
btn_no = { }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[cmp]
border = { fg = "#dc8a78" }
active = { reversed = true, fg = "#dc8a78" }
inactive = { fg = "#eff1f5" }
