
[manager]
cwd = { fg = "#c8c093" }
hovered = { reversed = true, bold = true }
preview_hovered = { underline = true }
find_keyword = { fg = "#98bb6c", italic = true }
find_position = { fg = "#ffa066", bg = "reset", italic = true }
marker_copied = { fg = "#98bb6c", bg = "#98bb6c" }
marker_cut = { fg = "#ff5c8f", bg = "#ff5c8f" }
marker_marked = { fg = "#c8c093", bg = "#c8c093" }
marker_selected = { fg = "#dcd7ba", bg = "#dcd7ba" }
tab_active = { fg = "#16161d", bg = "#c8c093" }
tab_inactive = { fg = "#c8c093", bg = "#2a2a37" }
tab_width = 1
count_copied = { fg = "#16161d", bg = "#98bb6c" }
count_cut = { fg = "#16161d", bg = "#ff5c8f" }
count_selected = { fg = "#16161d", bg = "#dcd7ba" }
border_symbol = "│"
border_style = { fg = "#727169" }

[mode]
normal_main = { fg = "#16161d", bg = "#c8c093", bold = true }
normal_alt = { fg = "#c8c093", bg = "#2a2a37" }
select_main = { fg = "#16161d", bg = "#ffa066", bold = true }
select_alt = { fg = "#c8c093", bg = "#2a2a37" }
unset_main = { fg = "#16161d", bg = "#98bb6c", bold = true }
unset_alt = { fg = "#c8c093", bg = "#2a2a37" }

[status]
sep_left = { open = "\ue0be", close = "\ue0b8" }
sep_right = { open = "\ue0be", close = "\ue0b8" }
overall = { }
progress_label = { fg = "#dcd7ba", bold = true }
progress_normal = { fg = "#2a2a37", bg = "#16161d" }
progress_error = { fg = "#ff5c8f", bg = "#16161d" }
perm_type = { fg = "#2a2a37" }
perm_read = { fg = "#98bb6c" }
perm_write = { fg = "#ff5c8f" }
perm_exec = { fg = "#98bb6c" }
perm_sep = { fg = "#727169" }

[pick]
border = { fg = "#c8c093" }
active = { fg = "#ff5c8f", bold = true }
inactive = { }

[input]
border = { fg = "#dcd7ba" }
title = { }
value = { }
selected = { reversed = true }

[tasks]
border = { fg = "#c8c093" }
title = { }
hovered = { underline = true }

[which]
mask = { bg = "#16161d" }
cand = { fg = "#c8c093" }
rest = { fg = "#727169" }
desc = { fg = "#ffa066" }
separator = "  "
separator_style = { fg = "#2a2a37" }

[help]
on = { fg = "#c8c093" }
run = { fg = "#ff5c8f" }
hovered = { reversed = true, bold = true }
footer = { fg = "#16161d", bg = "#c8c093" }

[notify]
title_info = { fg = "#98bb6c" }
title_warn = { fg = "#dcd7ba" }
title_error = { fg = "#ff5c8f" }

[filetype]
rules = [
  { mime = "image/*", fg = "#ff5c8f" },
  { mime = "{audio,video}/*", fg = "#98bb6c" },
  { mime = "application/*zip", fg = "#ff5c8f" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff5c8f" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#98bb6c" },
  { name = "*", fg = "#dcd7ba" },
  { name = "*/", fg = "#c8c093" },
]

[confirm]
border = { fg = "#c8c093" }
title = { fg = "#c8c093" }
content = { fg = "#dcd7ba" }
body = { fg = "red" }
list = { fg = "#dcd7ba" }
btn_yes = { reversed = true, fg = "#dcd7ba" }
btn_no = { }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[cmp]
border = { fg = "#c8c093" }
active = { reversed = true, fg = "#c8c093" }
inactive = { fg = "#dcd7ba" }
