# : Manager [[[

[mgr]
cwd = { fg = "#C1C497" }

# Tab
tab_active = { fg = "#23372B", bg = "#549E6A", bold = true }
tab_inactive = { fg = "#C1C497", bg = "#53685B" }
tab_width = 1

# Find
find_keyword = { fg = "#FF5345", bold = true, italic = true, underline = true }
find_position = { fg = "#FF5345", bold = true, italic = true }

# Marker
marker_copied = { fg = "#459451", bg = "#459451" }
marker_cut = { fg = "#9EEBB3", bg = "#9EEBB3" }
marker_marked = { fg = "#549E6A", bg = "#549E6A" }
marker_selected = { fg = "#3f634d", bg = "#3f634d" }

# Count
count_copied = { fg = "#111C18", bg = "#9EEBB3" }
count_cut = { fg = "#111C18", bg = "#9EEBB3" }
count_selected = { fg = "#23372B", bg = "#3f634d" }

# Border
border_symbol = " "
border_style  = { fg = "#549E6A" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#53685B", fg = "#549E6A" }

[mode]
# Mode
normal_main = { bg = "#549E6A", fg = "#23372B", bold = true }
normal_alt  = { bg = "#23372B", fg = "#C1C497" }

# Select mode
select_main = { bg = "#9EEBB3", fg = "#9EEBB3", bold = true }
select_alt  = { bg = "#23372B", fg = "#C1C497" }

# Unset mode
unset_main = { bg = "#3f634d", fg = "#9EEBB3", bold = true }
unset_alt  = { bg = "#23372B", fg = "#C1C497" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#549E6A", bg = "#23372B" }
progress_error = { fg = "#459451", bg = "#23372B" }

# Permissions
permissions_t = { fg = "#549E6A" }
permissions_w = { fg = "#3f634d" }
permissions_x = { fg = "#459451" }
permissions_r = { fg = "#C1C497" }
permissions_s = { fg = "#9EEBB3" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#549E6A" }
active = { fg = "#3f634d", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#549E6A" }
value = { fg = "#C1C497" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#549E6A", bold = true, bg = "#111C18" }
inactive = { fg = "#9EEBB3", bg = "#111C18" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#549E6A", bg = "#53685B" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#549E6A" }
title = {}
hovered = { fg = "#9EEBB3", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#23372B" }
cand = { fg = "#549E6A" }
rest = { fg = "#23372B" }
desc = { fg = "#C1C497" }
separator = " ‚ñ∂ "
separator_style = { fg = "#C1C497" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#C1C497" }
run = { fg = "#C1C497" }
footer = { fg = "#9EEBB3", bg = "#9EEBB3" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#3f634d" }
title_warn = { fg = "#549E6A" }
title_error = { fg = "#459451" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#3f634d" },

    # Media
    { mime = "{audio,video}/*", fg = "#549E6A" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#9EEBB3" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#C1C497" },

    # Special files
    { name = "*", is = "orphan", bg = "#459451" },
    { name = "*", is = "exec", fg = "#9EEBB3" },

    # Fallback
    { name = "*", fg = "#C1C497" },
    { name = "*/", fg = "#549E6A" },
]

# : ]]]
