colors:
  primary:
    background: '0x141415'
    foreground: '0xcdcdcd'
  normal:
    black:   '0x1c1c24'
    red:     '0xd8647e'
    green:   '0x7fa563'
    yellow:  '0xf3be7c'
    blue:    '0x6e94b2'
    magenta: '0xbb9dbd'
    cyan:    '0x7e98e8'
    white:   '0xcdcdcd'
  bright:
    black:   '0x606079'
    red:     '0xd8647e'
    green:   '0x7fa563'
    yellow:  '0xf3be7c'
    blue:    '0x6e94b2'
    magenta: '0xbb9dbd'
    cyan:    '0x7e98e8'
    white:   '0xcdcdcd'
