
[manager]
cwd = { fg = "#81A1C1" }
hovered = { reversed = true, bold = true }
preview_hovered = { underline = true }
find_keyword = { fg = "#A3BE8C", italic = true }
find_position = { fg = "#EBCB8B", bg = "reset", italic = true }
marker_copied = { fg = "#A3BE8C", bg = "#A3BE8C" }
marker_cut = { fg = "#BF616A", bg = "#BF616A" }
marker_marked = { fg = "#81A1C1", bg = "#81A1C1" }
marker_selected = { fg = "#D8DEE9", bg = "#D8DEE9" }
tab_active = { fg = "#2E3440", bg = "#81A1C1" }
tab_inactive = { fg = "#81A1C1", bg = "#3B4252" }
tab_width = 1
count_copied = { fg = "#2E3440", bg = "#A3BE8C" }
count_cut = { fg = "#2E3440", bg = "#BF616A" }
count_selected = { fg = "#2E3440", bg = "#D8DEE9" }
border_symbol = "│"
border_style = { fg = "#4C566A" }
[mode]
normal_main = { fg = "#2E3440", bg = "#81A1C1", bold = true }
normal_alt = { fg = "#81A1C1", bg = "#3B4252" }
select_main = { fg = "#2E3440", bg = "#EBCB8B", bold = true }
select_alt = { fg = "#81A1C1", bg = "#3B4252" }
unset_main = { fg = "#2E3440", bg = "#A3BE8C", bold = true }
unset_alt = { fg = "#81A1C1", bg = "#3B4252" }
[status]
sep_left = { open = "\ue0be", close = "\ue0b8" }
sep_right = { open = "\ue0be", close = "\ue0b8" }
overall = {}
progress_label = { fg = "#D8DEE9", bold = true }
progress_normal = { fg = "#3B4252", bg = "#2E3440" }
progress_error = { fg = "#BF616A", bg = "#2E3440" }
perm_type = { fg = "#3B4252" }
perm_read = { fg = "#A3BE8C" }
perm_write = { fg = "#BF616A" }
perm_exec = { fg = "#A3BE8C" }
perm_sep = { fg = "#4C566A" }
[pick]
border = { fg = "#81A1C1" }
active = { fg = "#BF616A", bold = true }
inactive = {}
[input]
border = { fg = "#D8DEE9" }
title = {}
value = {}
selected = { reversed = true }
[tasks]
border = { fg = "#3B4252" }
title = {}
hovered = { underline = true }
[which]
mask = { bg = "#3B4252" }
cand = { fg = "#81A1C1" }
rest = { fg = "#4C566A" }
desc = { fg = "#EBCB8B" }
separator = "  "
separator_style = { fg = "#3B4252" }
[help]
on = { fg = "#81A1C1" }
run = { fg = "#BF616A" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3B4252", bg = "#81A1C1" }
[notify]
title_info = { fg = "#A3BE8C" }
title_warn = { fg = "#D8DEE9" }
title_error = { fg = "#BF616A" }
[filetype]
rules = [
  { mime = "image/*", fg = "#BF616A" },
  { mime = "{audio,video}/*", fg = "#88C0D0" },
  { mime = "application/*zip", fg = "#BF616A" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#BF616A" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#A3BE8C" },
  { name = "*", fg = "#D8DEE9" },
  { name = "*/", fg = "#81A1C1" }
]
[confirm]
border = { fg = "#81A1C1" }
title = { fg = "#81A1C1" }
content = { fg = "#D8DEE9" }
body = { fg = "red" }
list = { fg = "#D8DEE9" }
btn_yes = { reversed = true, fg = "#D8DEE9" }
btn_no = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]
[cmp]
border = { fg = "#81A1C1" }
active = { reversed = true, fg = "#81A1C1" }
inactive = { fg = "#D8DEE9" }
