
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](color_wave_blue)\
$os\
[](bg:color_user fg:color_wave_blue)\
$username\
[](bg:color_folder fg:color_user)\
$directory\
[](bg:color_wave_blue fg:color_folder)\
[ ](color_wave_blue)\
"""

right_format = """
[](bg:color_wave_blue fg:color_bg1)\
[█](color_wave_blue)\
$cmd_duration\
$git_branch\
$git_status\
$docker_context\
$nodejs\
$php\
$rust\
$time\
[▓▒░](color_wave_blue)\
"""

palette = 'matte_black'

[palettes.matte_black]
color_bg0       = '#1e1e2e'
color_bg1       = '#2e2e3e'
color_bg2       = '#3e3e4e'
color_bg3       = '#4e4e5e'

color_fg0       = '#c5c5c5'
color_fg1       = '#aaaaaa'
color_comment   = '#888888'

color_wave_blue = '#5aa6f8'
color_user      = '#d18ee6'
color_folder    = '#f78c6c'

color_red       = '#f07178'
color_green     = '#c3e88d'
color_yellow    = '#ffcb6b'
color_blue      = '#82aaff'
color_purple    = '#c792ea'
color_cyan      = '#89ddff'
color_orange    = '#f78c6c'

color_bright_red     = '#f07178'
color_bright_green   = '#c3e88d'
color_bright_yellow  = '#ffcb6b'
color_bright_blue    = '#82aaff'
color_bright_purple  = '#c792ea'
color_bright_cyan    = '#89ddff'

color_git_add        = '#c3e88d'
color_git_change     = '#ffcb6b'
color_git_delete     = '#f07178'

[os]
disabled = false
format = '[ $symbol ]($style)'
style = 'bg:color_wave_blue fg:color_fg0'

[os.symbols]
Arch = "󰣇"
Alpine = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
openSUSE = " "
Pop = " "
SUSE = " "
Ubuntu = " "
Windows = " "


[username]
show_always = true
format = '[ $user ]($style)'
style_user = 'bg:color_user fg:color_bg0'
style_root = 'bg:color_cyan fg:color_bg0 bold'

[directory]
format = '[ $path ]($style)[$read_only]($read_only_style)'
style = 'bg:color_folder fg:color_bg0'
read_only = '󰌾 '
read_only_style = 'bg:color_folder fg:color_red dimmed'

[time]
disabled = false
format = '[ $time ]($style)'
time_format = '%R'
style = 'bg:color_wave_blue fg:color_fg0'

[cmd_duration]
format = '[  $duration ]($style)'
style = 'bg:color_bg3 fg:color_fg0'

[git_branch]
format = '[ $symbol$branch(:$remote_branch)]($style)'
style = 'bg:color_yellow fg:color_bg0'
symbol = '󰘬 '
truncation_length = 12

[git_status]
format = '[ $all_status$ahead_behind ]($style)'
style = 'bg:color_yellow fg:color_bg0'

[nodejs]
format = '[ $symbol($version) ]($style)'
style = 'bg:color_green fg:color_bg0'
not_capable_style = 'bg:color_red fg:color_bg0'

[php]
format = '[ $symbol ($version) ]($style)'
style = 'bg:color_purple fg:color_bg0'
symbol = ''

[rust]
format = '[ $symbol ($version) ]($style)'
style = 'bg:color_orange fg:color_bg0'
symbol = '󱘗'

[docker_context]
format = '[ $symbol $context ]($style)'
style = 'bg:color_cyan fg:color_bg0'
symbol = '󰡨'
