"$schema" = 'https://starship.rs/config-schema.json'
palette = 'Vague'

format = """
[](signature)\
$os\
$username\
[](bg:peach fg:signature)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:sapphire)\
$conda\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:signature fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:signature fg:crust"
style_root = "bg:signature fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.Catppuccin]
signature = "red" 
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.Catppuccin_Frappe]
signature = "red" 
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.Catppuccin_Latte]
signature = "red" 
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.Catppuccin_Macchiato]
signature = "red" 
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.Everforest]
signature = "green"
rosewater = "#e6c1ac"
flamingo = "#dfb4b4"
pink = "#e5b4d0"
mauve = "#c9a27e"
red = "#e67e80"
maroon = "#e69875"
peach = "#dbbc7f"
yellow = "#a7c080"
green = "#83c092"
teal = "#7fbbb3"
sky = "#89b482"
sapphire = "#7daea3"
blue = "#d699b6"
lavender = "#a7c080"
text = "#d3c6aa"
subtext1 = "#c5d1c5"
subtext0 = "#b5c1b5"
overlay2 = "#9da9a0"
overlay1 = "#8a9895"
overlay0 = "#7a8478"
surface2 = "#687078"
surface1 = "#53605c"
surface0 = "#445055"
base = "#2b3339"
mantle = "#272f35"
crust = "#22282e"

[palettes.Gruvbox]
signature = "yellow" 
rosewater = "#fbf1c7"
flamingo = "#f2e5bc"
pink = "#d3869b"
mauve = "#b16286"
red = "#fb4934"
maroon = "#cc241d"
peach = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
teal = "#8ec07c"
sky = "#83a598"
sapphire = "#458588"
blue = "#d3869b"
lavender = "#b8bb26"
text = "#ebdbb2"
subtext1 = "#d5c4a1"
subtext0 = "#bdae93"
overlay2 = "#a89984"
overlay1 = "#928374"
overlay0 = "#7c6f64"
surface2 = "#665c54"
surface1 = "#504945"
surface0 = "#3c3836"
base = "#282828"
mantle = "#1d2021"
crust = "#141617"

[palettes.Gruvbox_Material]
signature = "yellow" 
rosewater = "#f2e5bc"
flamingo = "#ebdbb2"
pink = "#d3869b"
mauve = "#b16286"
red = "#ea6962"
maroon = "#cc241d"
peach = "#e78a4e"
yellow = "#d8a657"
green = "#a9b665"
teal = "#89b482"
sky = "#7daea3"
sapphire = "#689d6a"
blue = "#7daea3"
lavender = "#a9b665"
text = "#d4be98"
subtext1 = "#c5b189"
subtext0 = "#b5a17a"
overlay2 = "#a89984"
overlay1 = "#928374"
overlay0 = "#7c6f64"
surface2 = "#665c54"
surface1 = "#514a41"
surface0 = "#3c3836"
base = "#282828"
mantle = "#1d2021"
crust = "#141617"

[palettes.Kanagawa]
signature = "blue" 
waveBlue2 = "#2D4F67" 
rosewater = "#dcd7ba"
flamingo = "#c8c093"
pink = "#957fb8"
mauve = "#7e9cd8"
red = "#c34043"
maroon = "#e82424"
peach = "#ff9e3b"
yellow = "#dca561"
green = "#76946a"
teal = "#6a9589"
sky = "#7fb4ca"
sapphire = "#658594"
blue = "#7e9cd8"
lavender = "#76946a"
text = "#dcd7ba"
subtext1 = "#c8c093"
subtext0 = "#a3a3a3"
overlay2 = "#727169"
overlay1 = "#54546d"
overlay0 = "#363646"
surface2 = "#2a2a37"
surface1 = "#1f1f28"
surface0 = "#16161d"
base = "#1f1f28"
mantle = "#181820"
crust = "#16161d"

[palettes.Matte_Black]
signature = "blue" 
rosewater = "#e0e0e0"
flamingo = "#d0d0d0"
pink = "#c397d8"
mauve = "#ae81ff"
red = "#f87070"
maroon = "#fb7373"
peach = "#ff8f40"
yellow = "#ffe16b"
green = "#79dcaa"
teal = "#70c0ba"
sky = "#5fb3b3"
sapphire = "#7ab0df"
blue = "#7ab0df"
lavender = "#79dcaa"
text = "#e0e0e0"
subtext1 = "#c0c0c0"
subtext0 = "#a0a0a0"
overlay2 = "#808080"
overlay1 = "#666666"
overlay0 = "#4d4d4d"
surface2 = "#404040"
surface1 = "#333333"
surface0 = "#262626"
base = "#121212"
mantle = "#0d0d0d"
crust = "#080808"

[palettes.Nightfox]
signature = "blue" 
rosewater = "#dfdfe0"
flamingo = "#d0d0d1"
pink = "#9d79d6"
mauve = "#719cd6"
red = "#c94f6d"
maroon = "#d16983"
peach = "#dbc074"
yellow = "#dbc074"
green = "#81b29a"
teal = "#63cdcf"
sky = "#719cd6"
sapphire = "#86abdc"
blue = "#719cd6"
lavender = "#81b29a"
text = "#cdcecf"
subtext1 = "#bebfc0"
subtext0 = "#afb0b1"
overlay2 = "#8c8fa1"
overlay1 = "#7c7f93"
overlay0 = "#6c6f85"
surface2 = "#5c5f77"
surface1 = "#4c4f69"
surface0 = "#393b44"
base = "#192330"
mantle = "#131c25"
crust = "#0d151c"

[palettes.Nord]
signature = "blue"
rosewater = "#eceff4"
flamingo = "#e5e9f0"
pink = "#b48ead"
mauve = "#a3be8c"
red = "#bf616a"
maroon = "#c06c75"
peach = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
teal = "#8fbcbb"
sky = "#88c0d0"
sapphire = "#81a1c1"
blue = "#5e81ac"
lavender = "#a3be8c"
text = "#eceff4"
subtext1 = "#e5e9f0"
subtext0 = "#d8dee9"
overlay2 = "#c0c5ce"
overlay1 = "#a7adba"
overlay0 = "#8f95a5"
surface2 = "#65737e"
surface1 = "#4c566a"
surface0 = "#434c5e"
base = "#2e3440"
mantle = "#242933"
crust = "#1a1e26"
frost_green = "#8fbcbb"
frost_blue = "#88c0d0"
frost_dark_blue = "#81a1c1"
frost_navy = "#5e81ac"

[palettes.Osaka]
signature = "blue" 
rosewater = "#f2f2f2"
flamingo = "#e8e8e8"
pink = "#c594c5"
mauve = "#5d99be"
red = "#ee6a70"
maroon = "#f08ba7"
peach = "#f0a45d"
yellow = "#e7c664"
green = "#91b362"
teal = "#5fb3b3"
sky = "#5fb3b3"
sapphire = "#5d99be"
blue = "#5d99be"
lavender = "#91b362"
text = "#f2f2f2"
subtext1 = "#e0e0e0"
subtext0 = "#cecece"
overlay2 = "#a6a6a6"
overlay1 = "#8a8a8a"
overlay0 = "#6e6e6e"
surface2 = "#525252"
surface1 = "#3d3d3d"
surface0 = "#292929"
base = "#1c1c1c"
mantle = "#141414"
crust = "#0c0c0c"

[palettes.Ristretto]
signature = "red" 
rosewater = "#c1a78e"
flamingo = "#b8a28c"
pink = "#945e80"
mauve = "#45707c"
red = "#c14a4a"
maroon = "#ea6962"
peach = "#c35e3a"
yellow = "#b4713e"
green = "#6c782e"
teal = "#4c7a5d"
sky = "#45707c"
sapphire = "#7daea3"
blue = "#45707c"
lavender = "#6c782e"
text = "#c1a78e"
subtext1 = "#b19e8a"
subtext0 = "#a19586"
overlay2 = "#766a5c"
overlay1 = "#695e52"
overlay0 = "#5c5248"
surface2 = "#4f463e"
surface1 = "#423a34"
surface0 = "#352e2a"
base = "#2d241e"
mantle = "#251e19"
crust = "#1d1813"

[palettes.Rosepine]
signature = "blue"
rosewater = "#e0def4"
flamingo = "#d8d7e4"
pink = "#c4a7e7"
mauve = "#31748f"
red = "#eb6f92"
maroon = "#eb6f92"
peach = "#f6c177"
yellow = "#f6c177"
green = "#31748f"
teal = "#9ccfd8"
sky = "#31748f"
sapphire = "#31748f"
blue = "#c4a7e7"
lavender = "#31748f"
text = "#e0def4"
subtext1 = "#d0ceda"
subtext0 = "#c0beca"
overlay2 = "#908caa"
overlay1 = "#6e6a86"
overlay0 = "#524f67"
surface2 = "#403d52"
surface1 = "#26233a"
surface0 = "#1f1d2e"
base = "#191724"
mantle = "#14121e"
crust = "#0f0d18"

[palettes.Rosepine_Darker]
signature = "blue"
rosewater = "#e0def4"
flamingo = "#d8d7e4"
pink = "#c4a7e7"
mauve = "#31748f"
red = "#eb6f92"
maroon = "#eb6f92"
peach = "#f6c177"
yellow = "#f6c177"
green = "#31748f"
teal = "#9ccfd8"
sky = "#31748f"
sapphire = "#31748f"
blue = "#c4a7e7"
lavender = "#31748f"
text = "#e0def4"
subtext1 = "#d0ceda"
subtext0 = "#c0beca"
overlay2 = "#908caa"
overlay1 = "#6e6a86"
overlay0 = "#56526e"
surface2 = "#44415a"
surface1 = "#2a283e"
surface0 = "#26233a"
base = "#1f1d2e"
mantle = "#1a1828"
crust = "#151322"

[palettes.Tokyonight]
signature = "blue" 
rosewater = "#c0caf5"
flamingo = "#b4befe"
pink = "#bb9af7"
mauve = "#7aa2f7"
red = "#f7768e"
maroon = "#f7768e"
peach = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
teal = "#73daca"
sky = "#7aa2f7"
sapphire = "#7aa2f7"
blue = "#7aa2f7"
lavender = "#9ece6a"
text = "#c0caf5"
subtext1 = "#a9b1d6"
subtext0 = "#9aa5ce"
overlay2 = "#565f89"
overlay1 = "#414868"
overlay0 = "#343b58"
surface2 = "#292e42"
surface1 = "#24283b"
surface0 = "#1f2335"
base = "#1a1b26"
mantle = "#16161e"
crust = "#121216"

[palettes.Vague]
signature = "#6e94b2"
rosewater = "#cdcdcd"
flamingo = "#c3c3d5"
pink = "#bb9dbd"
mauve = "#6e94b2"
red = "#d8647e"
maroon = "#d8647e"
peach = "#e8b589"
yellow = "#f3be7c"
green = "#7fa563"
teal = "#8abeb7"
sky = "#7e98e8"
sapphire = "#6e94b2"
blue = "#6e94b2"
lavender = "#7e98e8"
text = "#cdcdcd"
subtext1 = "#b8b8b8"
subtext0 = "#a5a5a5"
overlay2 = "#969896"
overlay1 = "#818181"
overlay0 = "#666666"
surface2 = "#525252"
surface1 = "#3d3d3d"
surface0 = "#292929"
base = "#141415"
mantle = "#101010"
crust = "#0a0a0a"

[palettes.Flexoki_Light]
paper = "#fffcf0"
signature = "#af3029"
rosewater = "#d14d41"
flamingo = "#da702c"
pink = "#d66990"
mauve = "#5e409d"
red = "#af3029"
maroon = "#a02f6f"
peach = "#d15f00"
yellow = "#ad8301"
green = "#66800b"
teal = "#24837b"
sky = "#3aa99f"
sapphire = "#205ea6"
blue = "#205ea6"
lavender = "#5e409d"
text = "#100f0f"
subtext1 = "#575653"
subtext0 = "#6f6e69"
overlay2 = "#878580"
overlay1 = "#9f9d98"
overlay0 = "#b7b5ac"
surface2 = "#ceccc0"
surface1 = "#e6e4d9"
surface0 = "#fffcf0"
base = "#fffcf0"
mantle = "#f2f0e5"
crust = "#e6e4d9"

[palettes.Flexoki_Dark]
paper = "#100f0f"
signature = "#d14d41"
rosewater = "#ffdad3"
flamingo = "#ffb381"
pink = "#ffa7d7"
mauve = "#c8a1ff"
red = "#d14d41"
maroon = "#e58eb2"
peach = "#ff802b"
yellow = "#ffc53d"
green = "#87b237"
teal = "#4abfaf"
sky = "#5dc0bd"
sapphire = "#3e8de0"
blue = "#3e8de0"
lavender = "#c8a1ff"
text = "#fffcf0"
subtext1 = "#e6e4d9"
subtext0 = "#ceccc0"
overlay2 = "#b7b5ac"
overlay1 = "#9f9d98"
overlay0 = "#878580"
surface2 = "#6f6e69"
surface1 = "#575653"
surface0 = "#403f3c"
base = "#100f0f"
mantle = "#1c1b1a"
crust = "#272524"
