# : Manager [[[

[mgr]
cwd = { fg = "#d3c6aa" }

# Tab
tab_active = { fg = "#343f44", bg = "#a7c080", bold = true }
tab_inactive = { fg = "#d3c6aa", bg = "#868d80" }
tab_width = 1

# Find
find_keyword = { fg = "#e67e80", bold = true, italic = true, underline = true }
find_position = { fg = "#e67e80", bold = true, italic = true }

# Marker
marker_copied = { fg = "#dbbc7f", bg = "#dbbc7f" }
marker_cut = { fg = "#9da9a0", bg = "#9da9a0" }
marker_marked = { fg = "#a7c080", bg = "#a7c080" }
marker_selected = { fg = "#5c6569", bg = "#5c6569" }

# Count
count_copied = { fg = "#272e33", bg = "#9da9a0" }
count_cut = { fg = "#272e33", bg = "#9da9a0" }
count_selected = { fg = "#343f44", bg = "#5c6569" }

# Border
border_symbol = " "
border_style  = { fg = "#a7c080" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#868d80", fg = "#a7c080" }

[mode]
# Mode
normal_main = { bg = "#a7c080", fg = "#343f44", bold = true }
normal_alt  = { bg = "#343f44", fg = "#d3c6aa" }

# Select mode
select_main = { bg = "#9da9a0", fg = "#343f44", bold = true }
select_alt  = { bg = "#343f44", fg = "#d3c6aa" }

# Unset mode
unset_main = { bg = "#5c6569", fg = "#343f44", bold = true }
unset_alt  = { bg = "#343f44", fg = "#d3c6aa" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a7c080", bg = "#343f44" }
progress_error = { fg = "#dbbc7f", bg = "#343f44" }

# Permissions
permissions_t = { fg = "#a7c080" }
permissions_w = { fg = "#5c6569" }
permissions_x = { fg = "#dbbc7f" }
permissions_r = { fg = "#d3c6aa" }
permissions_s = { fg = "#9da9a0" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a7c080" }
active = { fg = "#5c6569", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#a7c080" }
value = { fg = "#d3c6aa" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#a7c080", bold = true, bg = "#272e33" }
inactive = { fg = "#9da9a0", bg = "#272e33" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#a7c080", bg = "#868d80" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a7c080" }
title = {}
hovered = { fg = "#9da9a0", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343f44" }
cand = { fg = "#a7c080" }
rest = { fg = "#343f44" }
desc = { fg = "#d3c6aa" }
separator = " ‚ñ∂ "
separator_style = { fg = "#d3c6aa" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#d3c6aa" }
run = { fg = "#d3c6aa" }
footer = { fg = "#343f44", bg = "#9da9a0" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#5c6569" }
title_warn = { fg = "#a7c080" }
title_error = { fg = "#dbbc7f" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#5c6569" },

    # Media
    { mime = "{audio,video}/*", fg = "#a7c080" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#9da9a0" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#d3c6aa" },

    # Special files
    { name = "*", is = "orphan", bg = "#dbbc7f" },
    { name = "*", is = "exec", fg = "#9da9a0" },

    # Fallback
    { name = "*", fg = "#d3c6aa" },
    { name = "*/", fg = "#a7c080" },
]

# : ]]]
