
[manager]
cwd = { fg = "#8fbcbb" }
hovered = { reversed = true, bold = true }
preview_hovered = { underline = true }
find_keyword = { fg = "#a3be8c", italic = true }
find_position = { fg = "#ebcb8b", bg = "reset", italic = true }
marker_copied = { fg = "#a3be8c", bg = "#a3be8c" }
marker_cut = { fg = "#bf616a", bg = "#bf616a" }
marker_marked = { fg = "#8fbcbb", bg = "#8fbcbb" }
marker_selected = { fg = "#ebdbb2", bg = "#ebdbb2" }
tab_active = { fg = "#2e3440", bg = "#a3be8c" }
tab_inactive = { fg = "#a3be8c", bg = "#3b4252" }
tab_width = 1
count_copied = { fg = "#2e3440", bg = "#a3be8c" }
count_cut = { fg = "#2e3440", bg = "#bf616a" }
count_selected = { fg = "#2e3440", bg = "#ebdbb2" }
border_symbol = "│"
border_style = { fg = "#4c566a" }

[mode]
normal_main = { fg = "#2e3440", bg = "#a3be8c", bold = true }
normal_alt = { fg = "#a3be8c", bg = "#3b4252" }
select_main = { fg = "#2e3440", bg = "#ebcb8b", bold = true }
select_alt = { fg = "#a3be8c", bg = "#3b4252" }
unset_main = { fg = "#2e3440", bg = "#bf616a", bold = true }
unset_alt = { fg = "#a3be8c", bg = "#3b4252" }

[status]
sep_left = { open = "\ue0be", close = "\ue0b8" }
sep_right = { open = "\ue0be", close = "\ue0b8" }
overall = { }
progress_label = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#3b4252", bg = "#2e3440" }
progress_error = { fg = "#bf616a", bg = "#2e3440" }
perm_type = { fg = "#3b4252" }
perm_read = { fg = "#a3be8c" }
perm_write = { fg = "#bf616a" }
perm_exec = { fg = "#a3be8c" }
perm_sep = { fg = "#4c566a" }

[pick]
border = { fg = "#8fbcbb" }
active = { fg = "#bf616a", bold = true }
inactive = { }

[input]
border = { fg = "#ebdbb2" }
title = { }
value = { }
selected = { reversed = true }

[tasks]
border = { fg = "#a3be8c" }
title = { }
hovered = { underline = true }

[which]
mask = { bg = "#2e3440" }
cand = { fg = "#a3be8c" }
rest = { fg = "#4c566a" }
desc = { fg = "#ebcb8b" }
separator = "  "
separator_style = { fg = "#3b4252" }

[help]
on = { fg = "#a3be8c" }
run = { fg = "#bf616a" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2e3440", bg = "#a3be8c" }

[notify]
title_info = { fg = "#a3be8c" }
title_warn = { fg = "#ebdbb2" }
title_error = { fg = "#bf616a" }

[filetype]
rules = [
  { mime = "image/*", fg = "#bf616a" },
  { mime = "{audio,video}/*", fg = "#8fbcbb" },
  { mime = "application/*zip", fg = "#bf616a" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#bf616a" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#a3be8c" },
  { name = "*", fg = "#ebdbb2" },
  { name = "*/", fg = "#8fbcbb" },
]

[confirm]
border = { fg = "#a3be8c" }
title = { fg = "#a3be8c" }
content = { fg = "#ebdbb2" }
body = { fg = "red" }
list = { fg = "#ebdbb2" }
btn_yes = { reversed = true, fg = "#ebdbb2" }
btn_no = { }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[cmp]
border = { fg = "#a3be8c" }
active = { reversed = true, fg = "#a3be8c" }
inactive = { fg = "#ebdbb2" }
